site_name: Weave Docs
repo_url: https://github.com/Quadro1337/weave-docs

extra_css:
  - stylesheets/extra.css

theme:
  icon:
    repo: fontawesome/brands/github
  logo: assets/logo.svg
  favicon: assets/favicon.png
  name: material
  palette:
    scheme: slate
    primary: slate
    accent: slate
  font:
    text: Inter
    code: Source Code Pro
  features:
    - content.code.copy
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.footer
    - search.suggest
    - search.highlight
    - search.share

extra:
  generator: false
  social:
    - icon: fontawesome/brands/vk
      name: VK
      link: https://vk.com/weave_csgo

    - icon: fontawesome/brands/discord
      name: Discord
      link: https://discord.gg/dEKp7vqQeu

    - icon: fontawesome/brands/telegram
      name: Telegram
      link: https://t.me/weave_csgo

copyright: Weave Documentation
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - def_list
  - attr_list
  - md_in_html
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

nav:
  - ğŸš€ Getting started: index.md
  - ğŸ’¡ Events: events.md
  - ğŸŒ Namespaces:
    - ğŸ’¥ Anti-aim: namespaces/anti-aim.md
    - ğŸ“„ Convars: namespaces/convars.md
    - ğŸ§â€â™‚ï¸ Entity: namespaces/entity.md
    - ğŸ§© Global vars: namespaces/global-vars.md
    - ğŸ’­ Logs: namespaces/logs.md
    - ğŸª¢ Math: namespaces/math.md
    - âœ´ï¸ Cheat Vars: namespaces/cheat-vars.md
    - ğŸï¸ Render: namespaces/render.md
    - ğŸ§¾ UI: namespaces/ui.md
    - ğŸ’© Cheat: namespaces/cheat.md
    - ğŸ”— Client: namespaces/client.md
    - ğŸ² Script: namespaces/script.md
    - ğŸª¢ Hotkeys: namespaces/hotkeys.md
  - âœ¨ Types:
    - ğŸŒˆ Color: types/color.md
    - ğŸ“„ Convar: types/convar.md
    - ğŸ§â€â™‚ï¸ Entity: types/entity.md
    - ğŸ’¡ Event: types/event.md
    - ğŸ† Font: types/font.md
    - ğŸ§­ Texture: types/texture.md
    - âœ´ï¸ CheatVar: types/cheat-var.md
    - ğŸ”— Anti-aim settings: types/anti-aim-settings.md
    - ğŸŒƒ UserCmd: types/user-cmd.md
    - âš™ï¸ Vector: types/vector.md
    - ğŸª¢ Hotkey: types/hotkey.md
    - ğŸ§¾ UI:
      - âš™ï¸ Tab: types/ui/tab.md
      - âš™ï¸ Node: types/ui/node.md
      - âš™ï¸ Control: types/ui/control.md
      - âš™ï¸ Container: types/ui/container.md
      - ğŸ“‘ Controls:
        - ğŸ”— Checkbox: types/ui/controls/checkbox.md
        - ğŸ”— Slider: types/ui/controls/slider.md
        - ğŸ”— Dropbox: types/ui/controls/dropbox.md
        - ğŸ”— Color picker: types/ui/controls/color-picker.md
        - ğŸ”— Button: types/ui/controls/button.md